version: "3.8"

services:
  app:
    image: node:18
    container_name: cool-stack-app
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    command: >
      sh -c "npm install && npm run build && npm run start"

  postgres:
    image: postgres:15
    container_name: cool-stack-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coolstack_prod
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: cool-stack-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
